---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: app-demo
    env: production
spec:
  replicas: 4
  selector:
    matchLabels:
      app: app-demo
  template:
    metadata:
      labels:
        app: app-demo
    spec:
      containers:
      - name: app-demo
        image: newrejestr2018.azurecr.io/v1.0.0:1
        ports:
        - containerPort: 4000
      imagePullSecrets:
        - name: az-auth
---
apiVersion: v1
kind: Service
metadata:
  name: app-demo
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 4000
  selector:
    app: app-demo
